services:
  app:
    build: .
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: 'development'
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_SECURE_COOKIES: ''
      DB_HOST: 'db'
      DB_USER: 'root'
      DB_PASSWORD: 'mdbroot'
      S3_ENDPOINT_0: 'http://minio:9000/'
      S3_ENDPOINT_1: 'http://locahost:9000/'
      S3_REGION: 'amiverse'
      S3_BUCKET: 'development'
      S3_USER: 'minioroot'
      S3_PASSWORD: 'minioroot'
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: >
      bash -c "rm -f /app/tmp/pids/server.pid &&
      rm -rf /app/public/assets &&
      bundle install -j4 &&
      rails s -b 0.0.0.0"

  front:
    image: node:lts-alpine3.17
    tty: true
    stdin_open: true
    environment:
      WATCHPACK_POLLING: 'true'
      NEXT_PUBLIC_APPNAME: 'http://localhost:3001/'
      NEXT_PUBLIC_APINAME: 'http://localhost:3000/v1/'
      NEXT_PUBLIC_WSNAME: 'ws://localhost:3000/cable/'
    working_dir: /app
    volumes:
      - ./src2:/app
    ports:
      - '3001:3000'
    command: sh -c "npm install && npm update && npm run dev"

  db:
    image: mariadb:10.9.5
    environment:
      TZ: 'Asia/Tokyo'
      MARIADB_ROOT_PASSWORD: 'mdbroot'
    volumes:
      - db-vol:/var/lib/mysql
    stdin_open: true
    tty: true
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOSTS: 'db'
    ports:
      - '8080:80'
    stdin_open: true
    tty: true
    depends_on:
      - db

  minio:
    image: minio/minio
    volumes:
      - minio-vol:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: 'minioroot'
      MINIO_ROOT_PASSWORD: 'minioroot'
    stdin_open: true
    tty: true
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  db-vol:
  minio-vol: