services:
  app:
    build: .
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: 'development'
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_SECURE_COOKIES: ''
      API_URL: 'http://localhost:3000/v1/'
      DB_HOST: 'db'
      DB_USER: 'root'
      DB_PASSWORD: 'mdbroot'
      S3_ENDPOINT_0: 'http://minio:9000/'
      S3_ENDPOINT_1: 'http://localhost:9000/'
      S3_REGION: 'amiverse'
      S3_BUCKET: 'development'
      S3_USER: 'minioroot'
      S3_PASSWORD: 'minioroot'
      REDIS_URL: 'redis://redis:6379/'
      SIDEKIQ_USERNAME: 'sidekiqroot'
      SIDEKIQ_PASSWORD: 'sidekiqroot'
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - minio
      - redis
    command: >
      bash -c "rm -f /app/tmp/pids/server.pid &&
      rm -rf /app/public/assets &&
      gem cleanup &&
      bundle install -j4 &&
      rails s -b 0.0.0.0"

  front:
    image: node:lts
    tty: true
    stdin_open: true
    environment:
      WATCHPACK_POLLING: 'true'
      NEXT_PUBLIC_APPNAME: 'http://localhost:3001/'
      NEXT_PUBLIC_APINAME: 'http://localhost:3000/v1/'
      NEXT_PUBLIC_WSNAME: 'ws://localhost:3000/cable/'
    working_dir: /app
    volumes:
      - ./src2:/app
    ports:
      - '3001:3000'
    command: sh -c "npm install && npm update && npm run dev"

  db:
    image: mariadb:latest
    environment:
      TZ: 'Asia/Tokyo'
      MARIADB_ROOT_PASSWORD: 'mdbroot'
    volumes:
      - db-vol:/var/lib/mysql
    stdin_open: true
    tty: true
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOSTS: 'db'
    ports:
      - '8080:80'
    stdin_open: true
    tty: true
    depends_on:
      - db

  minio:
    image: minio/minio:latest
    volumes:
      - minio-vol:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: 'minioroot'
      MINIO_ROOT_PASSWORD: 'minioroot'
    stdin_open: true
    tty: true
    ports:
      - '9000:9000'
      - '9001:9001'

  redis:
    image: redis:latest
    volumes:
      - redis-vol:/data
    ports:
      - '6379:6379'

  rediscommander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: sidekiq:redis:6379,sidekiq2:redis:6379
      TZ: JST-9
    ports:
      - "8081:8081"
    depends_on:
      - redis

  sidekiq:
    build: .
    environment:
      DB_HOST: 'db'
      DB_USER: 'root'
      DB_PASSWORD: 'mdbroot'
      S3_ENDPOINT_0: 'http://minio:9000/'
      S3_ENDPOINT_1: 'http://localhost:9000/'
      S3_REGION: 'amiverse'
      S3_BUCKET: 'development'
      S3_USER: 'minioroot'
      S3_PASSWORD: 'minioroot'
      REDIS_URL: 'redis://redis:6379/'
      SIDEKIQ_USERNAME: 'sidekiqroot'
      SIDEKIQ_PASSWORD: 'sidekiqroot'
    working_dir: /app
    volumes:
      - ./src:/app
    depends_on:
      - redis
    command: >
      bash -c "bundle install -j4 &&
      bundle exec sidekiq -C config/sidekiq.yml"


volumes:
  db-vol:
  minio-vol:
  redis-vol: