name: Release to Production Environment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/amiverse
            docker-compose down
            git remote set-url origin https://kisana528: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@github.com/Kisana528/amiverse.git
            git fetch origin main
            git reset --hard origin/main
            docker-compose up -d --build
